/**
 * Deploy-target templates. Each target produces a self-contained artifact
 * that includes iii + the snoopy worker.
 *
 * The point: hide the "iii is separate infra" fact from the user. They
 * pick a target, we generate everything needed to run it.
 *
 *   docker   → Dockerfile that downloads iii + boots worker (single image)
 *   fly      → Dockerfile + fly.toml, ready to `fly deploy`
 *   node     → Plain Dockerfile + start.sh tarball; assumes user provides
 *              their own Node host (VM, ECS task, etc.)
 */
export type DeployTarget = "docker" | "fly" | "node";

export const TARGETS: DeployTarget[] = ["docker", "fly", "node"];

// Single source of truth for the iii release we ship in deploy artifacts.
// Keep in sync with packages/cli/src/iiiInstall.ts RELEASE_VERSION.
const III_RELEASE = "iii/v0.12.0";

/**
 * A single Dockerfile that bundles the iii binary and starts both the
 * engine and the worker. Used for `docker`, `fly`, and `node` targets —
 * the only thing that changes is which platform-specific wrappers we add.
 */
export function bundledDockerfile(): string {
  return `# Auto-generated by \`agent deploy --target <docker|fly|node>\`.
# Single image — bundles iii engine + snoopy worker. Edit freely.

FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --frozen-lockfile

FROM node:20-slim
WORKDIR /app

# --- iii engine -----------------------------------------------------------
# Download the Linux iii binary so the worker can connect to a local engine.
# Pin to ${III_RELEASE}; bump deliberately if you upgrade iii.
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \\
 && rm -rf /var/lib/apt/lists/* \\
 && ARCH=\$(dpkg --print-architecture) && TARGET=\$( \\
       case \$ARCH in \\
         amd64) echo x86_64-unknown-linux-gnu ;; \\
         arm64) echo aarch64-unknown-linux-gnu ;; \\
         *) echo "unsupported arch: \$ARCH" && exit 1 ;; \\
       esac) \\
 && curl -fsSL https://github.com/iii-hq/iii/releases/download/${III_RELEASE}/iii-\$TARGET.tar.gz \\
      | tar -xz -C /usr/local/bin

# --- worker code ----------------------------------------------------------
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Boot iii engine + worker in the same container. iii listens on 49134/3111;
# the worker connects locally. Override with III_WS_URL for split deploys.
ENV III_WS_URL=ws://localhost:49134
ENV III_HTTP_URL=http://localhost:3111

# Use a tiny init script so a crash in either process kills the container
# (Docker restart policy then re-runs both).
COPY scripts/start.sh /app/start.sh
RUN chmod +x /app/start.sh
EXPOSE 3111 49134
CMD ["/app/start.sh"]
`;
}

/** Init wrapper that boots iii then the snoopy worker. */
export function startScript(): string {
  return `#!/bin/sh
# Auto-generated by \`agent deploy\`. Boots iii then the snoopy worker.
set -e

# Background the engine.
iii --use-default-config --no-update-check &
IIIPID=\$!

# Trap signals so the container shuts down cleanly.
shutdown() {
  echo "Shutting down…"
  kill -TERM "\$IIIPID" 2>/dev/null || true
  wait "\$IIIPID" 2>/dev/null || true
  exit 0
}
trap shutdown INT TERM

# Wait for iii's HTTP port before starting the worker.
for i in 1 2 3 4 5 6 7 8 9 10; do
  if wget -q -O- http://localhost:3111/health >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

# Run the worker — \`agent dev\` with iii management disabled (we already
# started it) and docker disabled (we're inside a container).
exec npx agent dev --no-docker --no-iii
`;
}

/**
 * fly.toml — the smallest possible viable config. Users will tweak
 * regions and VM size, but this works out of the box.
 */
export function flyToml(appName: string): string {
  return `# Auto-generated by \`agent deploy --target fly\`. Edit before first deploy.
app = "${appName}"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3111
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# iii engine + snoopy worker run inside the same VM. iii writes state to
# local disk by default; for durability across machines, swap iii-state's
# backend to Redis/Postgres and provision them as fly addons.
`;
}

/** README the artifact ships with so users know what they've just got. */
export function targetReadme(target: DeployTarget, appName: string): string {
  if (target === "fly") {
    return `# ${appName} — Fly.io deploy

Generated by \`agent deploy --target fly\`.

\`\`\`bash
fly launch --no-deploy        # if you haven't created the app yet
fly secrets set OPENAI_API_KEY=…
fly deploy
\`\`\`

The image bundles iii + your worker. \`fly deploy\` ships both. Logs:
\`\`\`bash
fly logs
\`\`\`
`;
  }
  if (target === "node") {
    return `# ${appName} — Node host deploy

Generated by \`agent deploy --target node\`. Runs anywhere Docker runs.

\`\`\`bash
docker build -t ${appName} .
docker run --rm -p 3111:3111 -p 49134:49134 \\
  -e OPENAI_API_KEY=\$OPENAI_API_KEY \\
  ${appName}
\`\`\`
`;
  }
  return `# ${appName} — Docker

Generated by \`agent deploy --target docker\`.

\`\`\`bash
docker build -t ${appName} .
docker run --rm -p 3111:3111 -p 49134:49134 \\
  -e OPENAI_API_KEY=\$OPENAI_API_KEY \\
  ${appName}
\`\`\`

Push to a registry:
\`\`\`bash
agent deploy --target docker --build --registry ghcr.io/me
\`\`\`
`;
}
